# GM PAGES
landing_page:
  path: /guided-match/landing-page
  controller: App\Controller\LandingPageController::landingPage

question_page:
  path: /guided-match/journey/{journeyUuid}/{questionUuid}
  controller: App\Controller\GuideMatchJourneyController::journey

# Page routes
home:
  path: /
  controller: App\Controller\PageController::home

guide_match_journery:
  path: /gm/test-journey/
  controller: App\Controller\GuideMatchJourneyTestController:guideMatchJourney

  # Test redirect routes
test_redirect_routes:
  path: /gm/test/
  controller: App\Controller\TestController:index
