
# GM PAGES
landing_page:
  path: /guided-match/{journeyId}/landing-page
  controller: App\Controller\LandingPageController::landingPage 

question_page:
  path: /guided-match/journey/{journeyId}/{journeyInstanceId}/{questionUuid}/{gPage}
  controller: App\Controller\GuideMatchJourneyController::journey
  defaults:
    gPage: 0

result_page:
  path: /guided-match/result-page
  controller: App\Controller\ResultPageController::resultPage


# Tactical back to search
back_to_search:
  path: /guided-match/back-to-search-results/
  controller: App\Controller\TacticalSerchResultController:backToSearch

start-journey:
  path: /guided-match/start-journey/{journeyUuid}
  controller: App\Controller\StartJourneyController:startJourney

back-to-previous:
  path: /guided-match/journey-back/{journeyId}/{journeyInstanceId}/{questionUuid}/{journeyHistory}/{gPage}
  controller: App\Controller\GuideMatchBackToPreviousController::backToPrevious
  defaults:
    gPage: 0

journey-result:
  path: /guided-match/result/{journeyId}/{journeyInstanceId}/{agreements?}
  controller: App\Controller\GuideMatchJourneyResultController::journeyResult


contact-ccs-page:
  path: /guided-match/contact-css/{journeyId}/{journeyInstanceId}/{questionUuid}/{journeyHistory}/{gPage}
  controller: App\Controller\GuideMatchContactCssController::contactCss

guided-match-journeys:
  path: /guidedmatch
  controller: App\Controller\GuidedMatchJourneysController:searchJourneys

guided-match-health-check:
  path: /guided-match/health-check
  controller: App\Controller\GuidedMatchHealthCheckController:testHealth
  

delete-cache-files:
  path: /delete-cache-files
  controller: App\Controller\TestRemoveCacheController::deleteCacheFiles 

dwn-speed-raport:
  path: /dwn-speed-raport
  controller: App\Controller\SpeedRaportController:downloadLog

clear-speed-raport:
  path: /clear-speed-raport
  controller: App\Controller\SpeedRaportController:clearReport