# GM PAGES
landing_page:
  path: /guided-match/{slug}
  controller: App\Controller\GuidedMatchPagesController::landingPage

question_page:
  path: /guided-match/{slug}/questions
  controller: App\Controller\GuidedMatchPagesController::questionsPage

# Page routes
home:
  path: /
  controller: App\Controller\PageController::home
