test-wp:
  path: /wp
  controller: App\Controller\TestWordpressController::index

# GM PAGES
landing_page:
  path: /guided-match/landing-page
  controller: App\Controller\LandingPageController::landingPage 

question_page:
  path: /guided-match/journey/{journeyId}/{journeyInstanceId}/{questionUuid}/{gPage}
  controller: App\Controller\GuideMatchJourneyController::journey
  defaults:
    gPage: 0

result_page:
  path: /guided-match/result-page
  controller: App\Controller\ResultPageController::resultPage


# Page routes
home:
  path: /
  controller: App\Controller\PageController::home

guide_match_journery:
  path: /gm/test-journey/
  controller: App\Controller\GuideMatchJourneyTestController:guideMatchJourney

  # Test redirect routes
test_redirect_routes:
  path: /gm/test/
  controller: App\Controller\TestController:index

# Tactical back to search
back_to_search:
  path: /guided-match/back-to-search-results/
  controller: App\Controller\TacticalSerchResultController:backToSearch

start-journey:
  path: /guided-match/start-journey/{journeyUuid}
  controller: App\Controller\StartJourneyController:startJourney

back-to-previous:
  path: /guided-match/journey-back/{journeyId}/{journeyInstanceId}/{questionUuid}/{journeyHistory}/{gPage}
  controller: App\Controller\GuideMatchBackToPreviousController::backToPrevious
  defaults:
    gPage: 0

journey-result:
  path: /guided-match/result/{journeyId}/{journeyInstanceId}/{searchBy}/{journeyData}
  controller: App\Controller\GuideMatchJourneyResultController::journeyResult